.TH BLOBBY-SERVER 6 "August 1, 2007"
.SH NAME
blobby-server \- A volleyball game with blobs
.SH SYNOPSIS
\fBblobby-server\fR
.br
.SH DESCRIPTION
Server for the arcarde volleyball game with jumping blobs.
The port of the server is 1234.
.SH AUTHOR
This manual page was written by Felix Geyer <debfx-pkg@fobos.de>.
